[package]
name = "halogen-webui-view-downloads"
version.workspace = true
edition.workspace = true

[dependencies]
halogen-webui-hooks = { path = "../hooks" }
halogen-webui-episode-list-page = { path = "../episode-list-page" }
dioxus = { workspace = true, features = ["router"] }
halogen-webui-episode-list = { path = "../episode-list" }
url = { workspace = true }
chrono = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { workspace = true, features = ["Window", "Document", "Location", "History"] }

[dev-dependencies]
futures = { workspace = true }

[features]
web = ["dioxus/web", "halogen-webui-episode-list-page/web", "halogen-webui-episode-list/web", "halogen-webui-hooks/web"]
desktop = ["dioxus/desktop", "halogen-webui-episode-list-page/desktop", "halogen-webui-episode-list/desktop", "halogen-webui-hooks/desktop"]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true }
