[package]
name = "halogen-webui-player-controls"
version.workspace = true
edition.workspace = true

[dependencies]
halogen-format = { path = "../../crates/format" }
halogen-webui-hooks = { path = "../hooks" }
dioxus = { workspace = true, features = ["router"] }
halogen-webui-commands = { path = "../commands" }
halogen-webui-app-state = { path = "../app-state" }
halogen-webui-platform = { path = "../platform" }
halogen-webui-config = { path = "../config" }
halogen-webui-player = { path = "../player" }
halogen-webui-component-widgets = { path = "../component-widgets" }
halogen-webui-component-icons = { path = "../component-icons" }
halogen-wire = { path = "../../crates/wire" }
url = { workspace = true }
chrono = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { workspace = true, features = ["Window", "Document", "Location", "History"] }

[dev-dependencies]
futures = { workspace = true }

[features]
web = ["dioxus/web", "halogen-webui-app-state/web", "halogen-webui-commands/web", "halogen-webui-component-icons/web", "halogen-webui-component-widgets/web", "halogen-webui-config/web", "halogen-webui-hooks/web", "halogen-webui-platform/web", "halogen-webui-player/web"]
desktop = ["dioxus/desktop", "halogen-webui-app-state/desktop", "halogen-webui-commands/desktop", "halogen-webui-component-icons/desktop", "halogen-webui-component-widgets/desktop", "halogen-webui-config/desktop", "halogen-webui-hooks/desktop", "halogen-webui-platform/desktop", "halogen-webui-player/desktop"]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true }
