[package]
name    = "halogen-config"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
halogen-utils = { path = "../utils" }
halogen-wire  = { path = "../wire" }
clap = { version = "4", features = ["derive", "env"] }
chrono = { workspace = true }
serde = { workspace = true }
toml = "0.8"
directories = { workspace = true }
