[package]
name = "halogen-webui-logging"
version.workspace = true
edition.workspace = true

[dependencies]
halogen-logging-client = { path = "../../crates/logging-client" }
halogen-webui-platform = { path = "../platform" }
halogen-webui-store-idb = { path = "../store-idb" }
serde_json = { workspace = true }
anyhow = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
idb = { workspace = true }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = [
    "Window", "Document", "Element", "HtmlElement", "HtmlAnchorElement",
    "Blob", "BlobPropertyBag", "Url"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }

[features]
desktop = ["halogen-webui-platform/desktop"]
web = ["halogen-webui-platform/web"]
